# -*- coding: utf-8 -*-
"""T.Nikhitha,AIE23133,SP LAB 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NvW2DhwYUgEIiFRMy26AfSkSZFHF9QDR
"""

!pip install transformers torchaudio librosa g2p_en

import torch
import torchaudio
import librosa
import matplotlib.pyplot as plt
import numpy as np
from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC
from g2p_en import G2p
import nltk


nltk.download('averaged_perceptron_tagger_eng')
nltk.download('cmudict')


audio_path = "/content/LJ050-0274.wav"

waveform, sample_rate = torchaudio.load(audio_path)


if waveform.shape[0] > 1:
    waveform = torch.mean(waveform, dim=0, keepdim=True)


target_sr = 16000
if sample_rate != target_sr:
    resampler = torchaudio.transforms.Resample(sample_rate, target_sr)
    waveform = resampler(waveform)

speech = waveform.squeeze().numpy()
sample_rate = target_sr
duration = len(speech) / sample_rate

print("Processed Sample Rate:", sample_rate)
print("Duration:", duration)


processor = Wav2Vec2Processor.from_pretrained(
    "facebook/wav2vec2-base-960h"
)
model = Wav2Vec2ForCTC.from_pretrained(
    "facebook/wav2vec2-base-960h"
)
model.eval()


inputs = processor(
    speech,
    sampling_rate=16000,
    return_tensors="pt",
    padding=True
)

with torch.no_grad():
    logits = model(inputs.input_values).logits

predicted_ids = torch.argmax(logits, dim=-1)
transcription = processor.decode(predicted_ids[0])

print("\nRecognized Text:")
print(transcription)


g2p = G2p()
phonemes = g2p(transcription)


phonemes = [p for p in phonemes if p != " "]

print("\nConverted Phonemes:")
print(phonemes)


num_phonemes = len(phonemes)
time_per_phoneme = duration / num_phonemes


vowels = ["AA","AE","AH","AO","EH","IH","IY","UH","UW"]
fricatives = ["S","Z","SH","F","V","TH","DH","HH"]
plosives = ["P","B","T","D","K","G"]
approximants = ["Y","W","L","R"]

def classify_phoneme(p):
    if p in vowels:
        return "Vowel (Voiced, Periodic)"
    elif p in fricatives:
        return "Fricative (Turbulent Airflow)"
    elif p in plosives:
        return "Plosive (Air Burst)"
    elif p in approximants:
        return "Approximant (Smooth/Laminar)"
    else:
        return "Other"


for i, phoneme in enumerate(phonemes):

    start_time = i * time_per_phoneme
    end_time = start_time + time_per_phoneme

    start_sample = int(start_time * sample_rate)
    end_sample = int(end_time * sample_rate)

    segment = speech[start_sample:end_sample]

    if len(segment) == 0:
        continue

    category = classify_phoneme(phoneme)

    print("\nPhoneme:", phoneme)
    print("Category:", category)
    print("Start:", round(start_time,3),
          "End:", round(end_time,3))


    output_file = f"phoneme_{i}_{phoneme}.wav"
    torchaudio.save(
        output_file,
        torch.tensor(segment).unsqueeze(0),
        sample_rate
    )


    plt.figure(figsize=(7,3))
    plt.plot(segment)
    plt.title(f"{phoneme} | {category}")
    plt.xlabel("Samples")
    plt.ylabel("Amplitude")
    plt.grid()
    plt.show()

print("\nAll phonemes extracted successfully.")